In [1]:
# make sure how tf.nn.top_k works
# note: tf.where return a tensor with redundant 1 dimension

import tensorflow as tf
import numpy as np

config = tf.ConfigProto(allow_soft_placement=True)
config.gpu_options.per_process_gpu_memory_fraction = 0.40
sess = tf.InteractiveSession(config=config)

In [2]:
m = tf.constant(np.random.rand(10, 4))
print m.eval()

[[ 0.30855643  0.0107447   0.91636905  0.44848422]
 [ 0.01029674  0.1352565   0.07343978  0.86560538]
 [ 0.79171092  0.7055218   0.81898806  0.77889865]
 [ 0.40905475  0.96215466  0.57835041  0.32891823]
 [ 0.6326807   0.43605883  0.05710362  0.42334645]
 [ 0.55410533  0.54921449  0.06856669  0.11539495]
 [ 0.34798356  0.23122613  0.71717625  0.49474662]
 [ 0.126275    0.35067437  0.36891203  0.98862398]
 [ 0.4405645   0.56181611  0.00635853  0.44115811]
 [ 0.39241152  0.793026    0.08580658  0.71665797]]


In [45]:
print tf.shape(m).eval()
s = tf.reduce_sum(m, reduction_indices=[1])
print s.eval()
m_top5, inds = tf.nn.top_k(s, 5)
m_top5_ = tf.gather(s, inds)
print inds.eval()
print m_top5.eval()
print m_top5_.eval()

[10  4]
[ 1.6841544   1.0845984   3.09511943  2.27847805  1.54918959  1.28728146
  1.79113256  1.83448538  1.44989725  1.98790207]
[2 3 9 7 6]
[ 3.09511943  2.27847805  1.98790207  1.83448538  1.79113256]
[ 3.09511943  2.27847805  1.98790207  1.83448538  1.79113256]


In [13]:
# tf.minimum()
top_k = tf.minimum(tf.shape(m)[0] / 3, 5)
s = tf.reduce_sum(m, reduction_indices=[1])
print 's is ', s.eval()
m_top, inds = tf.nn.top_k(s, top_k)
m_top_ = tf.gather(s, inds)
print 'top ' + str(top_k.eval()), ' is:'
print m_top.eval()
print m_top_.eval()

s is  [ 1.6841544   1.0845984   3.09511943  2.27847805  1.54918959  1.28728146
  1.79113256  1.83448538  1.44989725  1.98790207]
top 3  is:
[ 3.09511943  2.27847805  1.98790207]
[ 3.09511943  2.27847805  1.98790207]


In [40]:
# gather 2 dimensional tensor
help(tf.gather)
g = tf.constant(np.random.rand(5, 4, 3))
label = tf.constant(np.random.randint(3, size=(10)) - 1)
x = tf.constant(np.random.rand(10, 4))
print (label.eval())
print (x.eval())

Help on function gather in module tensorflow.python.ops.gen_array_ops:

gather(params, indices, validate_indices=None, name=None)
    Gather slices from `params` according to `indices`.
    
    `indices` must be an integer tensor of any dimension (usually 0-D or 1-D).
    Produces an output tensor with shape `indices.shape + params.shape[1:]` where:
    
        # Scalar indices
        output[:, ..., :] = params[indices, :, ... :]
    
        # Vector indices
        output[i, :, ..., :] = params[indices[i], :, ... :]
    
        # Higher rank indices
        output[i, ..., j, :, ... :] = params[indices[i, ..., j], :, ..., :]
    
    If `indices` is a permutation and `len(indices) == params.shape[0]` then
    this operation will permute `params` accordingly.
    
    <div style="width:70%; margin:auto; margin-bottom:10px; margin-top:20px;">
    <img style="width:100%" src="../../images/Gather.png" alt>
    </div>
    
    Args:
      params: A `Tensor`.
      indices: A `Tensor`. 

In [44]:
keeps_cls = tf.where(tf.not_equal(label, -1))
# notice the tf.where return a tensor with the shape of [N, 1]
print tf.shape(label).eval(), tf.shape(keeps_cls).eval()
keeps_cls = tf.reshape(keeps_cls, [-1])
print keeps_cls.eval().shape
label_valid = tf.gather(label, keeps_cls)
print 'kept label index is', keeps_cls.eval()
print 'kept label is', label_valid.eval()
x_valid = tf.gather(x, keeps_cls)
print x_valid.eval().shape
print 'valid x is', x_valid.eval() 

[10] [6 1]
(6,)
kept label index is [0 1 5 7 8 9]
kept label is [1 1 0 1 0 1]
(6, 4)
valid x is [[ 0.45953898  0.13431683  0.99159979  0.64938353]
 [ 0.31972649  0.6739822   0.17844033  0.93756746]
 [ 0.27480661  0.69575193  0.18817153  0.44912241]
 [ 0.31764399  0.65743683  0.2870562   0.54659029]
 [ 0.93020952  0.64525706  0.59462619  0.64812553]
 [ 0.98845242  0.96618147  0.4901435   0.6247546 ]]
